configfile: "config/v1.yaml"

singularity: "docker://aalzhang/spectrum-master-rstudio:v1.0"

rule all:
    input:
        expand(
            normalized='{workdir}/sce_normalized/{{dataset}}.rds'.format(workdir=config['workdir']),
            dataset=config['dataset']
        )


# Filter and normalize SingleCellExperiment
rule preprocess_sce:
    input:
        raw=lambda wildcards: config['datasets'][wildcards.dataset],
    output:
        normalized='{workdir}/sce_normalized/{{dataset}}.rds'.format(workdir=config['workdir']),
    params:
        name='preprocess-sce-{dataset}',
        mito_thres=config['preprocessing'][wildcards.dataset]['max_mito'],
        ribo_thres=config['preprocessing'][wildcards.dataset]['max_ribo'],
        umap_neighbors=config['preprocessing'][wildcards.dataset]['umap_neighbors'],
        umap_min_dist=config['preprocessing'][wildcards.dataset]['umap_min_dist'],
    log:
        '{logdir}/logs/preprocess_sce/{{dataset}}.log'.format(logdir=config['logdir'])
    benchmark:
        '{logdir}/benchmarks/preprocess_sce/{{dataset}}.txt'.format(logdir=config['logdir'])
    shell:
        'Rscript R/preprocess_sce.R '
        '--sce {input.hgsc_raw} '
        '--mito_thres {params.mito_thres} '
        '--ribo_thres {params.ribo_thres} '
        '--umap_neighbors {params.umap_neighbors} '
        '--umap_min_dist {params.umap_min_dist} '
        '--outfname {output} '
        '>& {log}'