---
title: "Simulate from splatter model"
output: 
  html_document:
    toc: true
    toc_depth: 5
---


```{r global_chunk_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, warning = FALSE, message = FALSE, cache = FALSE)
```

```{r}
library(tidyverse)
library(scater)
library(scran)
library(R.utils)
library(pheatmap)

library(splatter)
library(scrna.utils)
library(cellassign)
library(cellassign.utils)
```

## Default parameters

```{r}
num_groups <- 4
num_batches <- 1
num_cells <- 500
group_probs <- c(0.3, 0.1, 0.3, 0.3)
batch_probs <- c(1)
de_facscale <- 0.04
de_facloc <- 0.02
de_nu <- 1
de_min <- 1
de_max <- 1000
batch_facscale <- 1
batch_facloc <- 1
de_prob <- 0.4
down_prob <- 0.5
seed <- 19279
base_sce_param_file <- '/datadrive/projects/cellassign-paper/pipelines/cellassign-sim-comparison/data/sce_t4k_params.rds'
```

## Estimate parameters

```{r}
model_params <- readRDS(base_sce_param_file)
```

## Generate extra parameters

```{r}
group_probs <- group_probs/sum(group_probs)
batch_probs <- batch_probs/sum(batch_probs)

print(group_probs)
print(batch_probs)
```

```{r}
batch_cell_counts <- round(batch_probs * num_cells, 0)
```

## Simulate data from parameters

```{r}
num_cells <- sum(batch_cell_counts)
```

```{r}
model_params_modified <- model_params

model_params_modified@nCells <- num_cells
model_params_modified@de.prob <- de_prob
model_params_modified@de.downProb <- down_prob
model_params_modified@nBatches <- num_batches
model_params_modified@nGroups <- num_groups
model_params_modified@batchCells <- batch_cell_counts
model_params_modified@group.prob <- group_probs

model_params_modified@de.facLoc <- de_facloc
model_params_modified@de.facScale <- de_facscale
model_params_modified@de.facNu <- de_nu
model_params_modified@de.max <- de_max
model_params_modified@de.min <- de_min
model_params_modified@batch.facLoc <- batch_facloc
model_params_modified@batch.facScale <- batch_facscale

model_params_modified@seed <- seed
```

```{r}
sce_sim_raw <- splatSimulate(params = model_params_modified, method = "groups", verbose = TRUE)
```

## Add on a few terrible cells

```{r}
set.seed(9001)
sce_sim <- sce_sim_raw

nbad <- 10
groups <- c("Group1", "Group4")

extra_cells_counts <- do.call('cbind', lapply(1:nbad, function(i) {
  mean_counts <- lapply(groups, function(grp) {
    sce_subset <- sce_sim %>% 
      scater::filter(Group == grp)
    sce_subset <- sce_subset[,sample(1:ncol(sce_subset), size = 1)]
    return(rowMeans(counts(sce_subset)))
  })
  count <- round(do.call('+', mean_counts)/length(mean_counts))
  return(count)
}))
colnames(extra_cells_counts) <- paste0("Cell", (ncol(sce_sim)+1):(ncol(sce_sim)+nbad))

extra_cells_coldata <- data.frame(
  Cell = paste0("Cell", (ncol(sce_sim)+1):(ncol(sce_sim)+nbad)),
  Batch = "Batch1",
  Group = paste(groups, collapse = "-"),
  ExpLibSize = NA
) %>% DataFrame()
rownames(extra_cells_coldata) <- extra_cells_coldata$Cell

extra_cells_sce <- SingleCellExperiment(
  assays = list(counts = extra_cells_counts),
  colData = extra_cells_coldata
)

assays(sce_sim) <- list(counts=assay(sce_sim, "counts"))

sce_sim <- cbind(sce_sim, extra_cells_sce)
```

## Normalize data

```{r}
sce_sim <- normalize_sce_sim(sce_sim, run_dimred = TRUE)
sce_sim <- runUMAP(sce_sim, use_dimred = 'PCA', n_dimred = 50, ncomponents = 2)
```

## CellAssign

```{r}
markers_to_use <- select_markers(sce_sim, percentile_fc = 0.95, percentile_meanexpr = 0.9, frac_genes = 1, max_genes_per_class = 15)

rho <- create_rho_matrix(sce_sim, markers_to_use, wrong_proportion = 0)

s <- sizeFactors(sce_sim)
B <- 20
X <- NULL

res <- cellassign_em(exprs_obj = sce_sim[rownames(rho),], s = s, rho = rho, X = X, B = B, use_priors = FALSE, prior_type = "shrinkage", delta_variance_prior = FALSE, verbose = FALSE, em_convergence_thres = 1e-5, min_delta = 0, num_runs = 1)

sce_sim$cluster <- str_replace(res$cell_type, "^DEFac", "") %>%
  plyr::mapvalues(paste0("Group", c(1:4)),
                  c("T cell", "B cell", "Tumor cell", "Fibroblast"))
```

```{r}
colour_map <- c(
  'T cell'='#0055d4',
  'B cell'='#782121',
  'Tumor cell'='#008033',
  'Fibroblast'='#442178'
)

dr_plot <- plotTSNE(sce_sim, ncomponents = 2, colour_by = "cluster", add_ticks = FALSE) + 
  guides(fill = FALSE) + 
  xlab("") + 
  ylab("") +
  theme(axis.text = element_blank()) + 
  scale_fill_manual(values = colour_map)

pdf("/datadrive/projects/cellassign-paper/drawings/v3/components/dr_plot.pdf", width = 3, height = 3)
dr_plot
dev.off()
```

```{r, echo = FALSE}
set.seed(101)

uncertain_group_vals <- pmax(pmin(rnorm(n = 2, mean = 0.5, sd = 0.05), 1), 0)
extra_rows <- data.frame(DEFacGroup1=uncertain_group_vals, DEFacGroup2=0, DEFacGroup3=0, DEFacGroup4=1-uncertain_group_vals)

pdf("/datadrive/projects/cellassign-paper/drawings/v3/components/probs.pdf", width = 3, height = 5, onefile = FALSE)
pheatmap(rbind(res$mle_params$gamma[sample(1:nrow(res$mle_params$gamma),18),], extra_rows)[sample(1:20, size = 20),], legend = FALSE, cluster_rows = FALSE, cluster_cols = FALSE, border_color = NA, show_colnames = FALSE, show_rownames = FALSE)
dev.off()
```

```{r}
example_marker_list <- list(
  'T cell'=c('CD2', 'CD3', 'CD45'),
  'B cell'=c('CD19', 'CD20', 'CD79A', 'CD45'),
  'Tumor cell'=c('EPCAM'),
  'Fibroblast'=c('COL1A1', 'ACTA2', 'THY90')
)

example_rho <- marker_list_to_mat(example_marker_list, include_other = FALSE)

example_rho_df <- example_rho %>%
  reshape2::melt() %>%
  dplyr::rename(gene=Var1, celltype=Var2, entry=value)
```

```{r, echo = FALSE}
marker_binary_plot <- ggplot(example_rho_df, aes(x=gene, y=celltype)) + 
  geom_tile(aes(fill=factor(entry)), colour='black', size = 1) + 
  theme_bw() + 
  theme_Publication() + 
  theme_nature() + 
  xlab("") +
  ylab("") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, face = 'bold', size = 10, family = 'Helvetica'),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_blank()) +
  scale_fill_manual(values = c('0'='#FFFFFF', '1'='#000000')) + 
  guides(fill = FALSE) + 
  coord_fixed(ratio = 1)

pdf("/datadrive/projects/cellassign-paper/drawings/v3/components/marker_plot.pdf", width = 6, height = 3)
marker_binary_plot
dev.off()
```

## Random viridis matrix

```{r}
set.seed(1483)

nrow <- 6
ncol <- 6
mat <- rnorm(n = nrow * ncol, mean = 100, sd = 20) %>% matrix(nrow = nrow, ncol = ncol)

pdf("/datadrive/projects/cellassign-paper/drawings/v3/components/expr_heat.pdf", width = 3, height = 3)
pheatmap(mat, legend = FALSE, cluster_rows = FALSE, cluster_cols = FALSE, border_color = NA, show_colnames = FALSE, show_rownames = FALSE, color = viridisLite::viridis(n = 100))
dev.off()
```