
configfile: 'config/v1.yaml'

singularity: "docker://alzhang/spectrum-master-rstudio:v1.3"

def get_final_outputs(wildcards):
    output_files = []
    
    for clust_method in config['cluster_settings']['clustering_methods']:
        for marker_setting in config['cluster_settings']['clustering_methods'][wildcards.clust_method]:
            output_files = output_files + expand(
                '{outdir}/cluster_sce/{{de_prob}}_{{down_prob}}_{{seed}}/{clust_method}_{marker_setting}_{{max_genes}}_{{wrong_prop}}.tsv'.format(
                    outdir=config['outdir'],
                    clust_method=clust_method,
                    marker_setting=marker_setting
                ),
                de_prob=config['simulation_settings']['variables']['de_prob'],
                down_prob=config['simulation_settings']['variables']['down_prob'],
                seed=config['simulation_settings']['variables']['seed'],
                max_genes=config['cluster_settings']['max_genes'],
                wrong_prop=config['cluster_settings']['wrong_marker_proportion']
            )
    
    return output_files

rule all:
    input:
        expand(
            '{outdir}/simulated_sce/sce_{{de_prob}}_{{down_prob}}_{{seed}}.rds'.format(outdir=config['workdir']),
            de_prob=config['simulation_settings']['variables']['de_prob'],
            down_prob=config['simulation_settings']['variables']['down_prob'],
            seed=config['simulation_settings']['variables']['seed']
        ),
        get_final_outputs,

rule create_sce:
    input:
        base_params=config['simulation_settings']['constants']['base_params'],
    output:
        sce='{outdir}/simulated_sce/sce_{{de_prob}}_{{down_prob}}_{{seed}}.rds'.format(outdir=config['workdir']),
    params:
        name='create-sce-{seed}-{de_prob}-{down_prob}',
        random_seed='{seed}',
        sim_model='splat',
        num_cells=config['simulation_settings']['constants']['num_cells'],
        num_groups=config['simulation_settings']['constants']['num_groups'],
        num_batches=config['simulation_settings']['constants']['num_batches'],
        group_probs=config['simulation_settings']['constants']['group_probs'],
        batch_probs=config['simulation_settings']['constants']['batch_probs'],
        de_facloc=config['simulation_settings']['constants']['de_facloc'],
        de_facscale=config['simulation_settings']['constants']['de_facscale'],
        de_nu=config['simulation_settings']['constants']['de_nu'],
        de_min=config['simulation_settings']['constants']['de_min'],
        de_max=config['simulation_settings']['constants']['de_max'],
        batch_facloc=config['simulation_settings']['constants']['batch_facloc'],
        batch_facscale=config['simulation_settings']['constants']['batch_facscale'],
        de_prob='{de_prob}',
        down_prob='{down_prob}',
    log:
        '{logdir}/logs/create_sce/{{de_prob}}_{{down_prob}}/{{seed}}.log'.format(logdir=config['logdir']),
    benchmark:
        '{logdir}/benchmarks/create_sce/{{de_prob}}_{{down_prob}}/{{seed}}.txt'.format(logdir=config['logdir']),
    shell:
        'Rscript R/create_sce.R '
        '--params {input.base_params} '
        '--outfname {output.sce} '
        '--seed {params.random_seed} '
        '--sim_model {params.sim_model} '
        '--num_cells {params.num_cells} '
        '--num_groups {params.num_groups} '
        '--num_batches {params.num_batches} '
        '--group_probs {params.group_probs} '
        '--batch_probs {params.batch_probs} '
        '--de_facloc {params.de_facloc} '
        '--de_facscale {params.de_facscale} '
        '--de_nu {params.de_nu} '
        '--de_min {params.de_min} '
        '--de_max {params.de_max} '
        '--batch_facloc {params.batch_facloc} '
        '--batch_facscale {params.batch_facscale} '
        '--de_prob {params.de_prob} '
        '--down_prob {params.down_prob} '
        '>& {log}'

rule cluster_sce:
    input:
        sce='{outdir}/simulated_sce/sce_{{de_prob}}_{{down_prob}}_{{seed}}.rds'.format(outdir=config['workdir']),
    output:
        clust_results='{outdir}/cluster_sce/{{de_prob}}_{{down_prob}}_{{seed}}/{{clust_method}}_{{marker_setting}}_{{max_genes}}_{{wrong_prop}}.tsv'.format(outdir=config['outdir']),
    params:
        name='cluster-sce-{seed}-{de_prob}-{down_prob}-{clust_method}-{marker_setting}-{max_genes}-{wrong_prop}',
        dimreduce_method=config['cluster_settings']['dimreduce_method'],
        conda_env=config['cluster_settings']['conda_env'],
        fc_percentile=config['cluster_settings']['fc_percentile'],
        expr_percentile=config['cluster_settings']['expr_percentile'],
        frac_genes=config['cluster_settings']['frac_genes'],
        test_proportion=config['cluster_settings']['test_proportion'],
        clust_method='{clust_method}',
        max_genes='{max_genes}',
        wrong_prop='{wrong_prop}',
        marker_settings='{marker_setting}',
    log:
        '{logdir}/logs/cluster_sce/{{de_prob}}_{{down_prob}}_{{seed}}/{{clust_method}}_{{marker_setting}}_{{max_genes}}_{{wrong_prop}}.log'.format(logdir=config['logdir']),
    benchmark:
        '{logdir}/benchmarks/cluster_sce/{{de_prob}}_{{down_prob}}_{{seed}}/{{clust_method}}_{{marker_setting}}_{{max_genes}}_{{wrong_prop}}.txt'.format(logdir=config['logdir']),
    shell:
        'Rscript R/cluster_sce.R '
        '--sce {input.sce} '
        '--outdir {output.clust_results} '
        '--dimreduce_method {params.dimreduce_method} '
        '--conda_env {params.conda_env} '
        '--fc_percentile {params.fc_percentile} '
        '--expr_percentile {params.expr_percentile} '
        '--frac_genes {params.frac_genes} '
        '--test_proportion {params.test_proportion} '
        '--clust_method {params.clust_method} '
        '--max_genes {params.max_genes} '
        '--wrong_prop {params.wrong_prop} '
        '--marker_setting {params.marker_setting} '
        '>& {log}'

rule evaluate_cluster:
    input:


# rule cellassign_sce:
#     input:
    
#     output:
    
#     params:

    
    