workdir: /datadrive/projects/cellassign-paper/results/scratch/external/v1
outdir: /datadrive/projects/cellassign-paper/results/outputs/external/v1
logdir: /datadrive/projects/cellassign-paper/results/logs/external/v1

koh_data:
  bulkrna_de: /datadrive/data/external/scrna/koh/SD_bulkRNA_DE_annotated.csv

koh_analysis:
  celltypes:
    - hESC
    - APS
    - MPS
    - DLL1pPXM
    - ESMT
    - Sclrtm
    - D5CntrlDrmmtm
    - D2LtM
  clustering_methods:
    - seurat_0.4
    - seurat_0.8
    - seurat_1.2
    - SC3
    - phenograph
  marker_quantile: 0.8