
# Directories
workdir: '/datadrive/projects/cellassign-paper/results/scratch/model_fitting/v1'
outdir: '/datadrive/projects/cellassign-paper/results/outputs/model_fitting/v1'
logdir: '/datadrive/projects/cellassign-paper/results/logs/model_fitting/v1'

models:
  - splatter
  - v3

datasets:
  pbmc68k:
    foreground: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/pbmc68k_markers.feather'
    background: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/pbmc_68k_normal_logfcs.feather'
    class1: Naive\ CD8+
    class2: Naive\ CD4+
  pbmc68k_b_cd8:
    foreground: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/pbmc68k_markers.feather'
    background: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/pbmc_68k_normal_logfcs.feather'
    class1: B
    class2: CD8+
  koh_aps_mps:
    foreground: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/koh_markers.feather'
    background: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/koh_normal_logfcs.feather'
    class1: APS
    class2: MPS
  koh_d2ltm_dll1ppxm:
    foreground: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/koh_markers.feather'
    background: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/koh_normal_logfcs.feather'
    class1: D2LtM
    class2: DLL1pPXM
  koh_hesc_esmt:
    foreground: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/koh_markers.feather'
    background: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/koh_normal_logfcs.feather'
    class1: hESC
    class2: ESMT
