
# Directories
workdir: '/datadrive/projects/cellassign-paper/results/scratch/model_fitting/v1'
outdir: '/datadrive/projects/cellassign-paper/results/outputs/model_fitting/v1'
logdir: '/datadrive/projects/cellassign-paper/results/logs/model_fitting/v1'

models:
  - splatter
  - v3

datasets:
  pbmc68k:
    foreground: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/pbmc68k_markers.feather'
    background: '/datadrive/projects/cellassign-paper/intermediates/bayesian_deprob/pbmc_68k_normal_logfcs.feather'
    class1: Naive\ CD8+
    class2: Naive\ CD4+