# Directories
workdir: '/datadrive/projects/cellassign-paper/results/scratch/benchmarking/v1'
outdir: '/datadrive/projects/cellassign-paper/results/outputs/benchmarking/v1'
logdir: '/datadrive/projects/cellassign-paper/results/logs/benchmarking/v1'

base_sce_param_file: /datadrive/projects/cellassign-paper/pipelines/cellassign-sim-comparison/data/sce_t4k_params.rds
seeds:
  - 1483

simulation_settings:
  cells_1000_groups_2:
    num_cells: 1000
    num_groups: 2
    num_batches: 1
    num_genes: 1000
    group_probs: 0.5,0.5
    batch_probs: "1"
    de_facloc: 0.0400
    de_facscale: 0.0237
    de_nu: 0.959
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    de_prob: 1
    down_prob: 0.5
    sim_model: splat
  cells_10000_groups_2:
    num_cells: 10000
    num_groups: 2
    num_batches: 1
    num_genes: 1000
    group_probs: 0.5,0.5
    batch_probs: "1"
    de_facloc: 0.0400
    de_facscale: 0.0237
    de_nu: 0.959
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    de_prob: 1
    down_prob: 0.5
    sim_model: splat
  cells_100000_groups_2:
    num_cells: 100000
    num_groups: 2
    num_batches: 1
    num_genes: 1000
    group_probs: 0.5,0.5
    batch_probs: "1"
    de_facloc: 0.0400
    de_facscale: 0.0237
    de_nu: 0.959
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    de_prob: 1
    down_prob: 0.5
    sim_model: splat
  cells_1000000_groups_2:
    num_cells: 1000000
    num_groups: 2
    num_batches: 1
    num_genes: 1000
    group_probs: 0.5,0.5
    batch_probs: "1"
    de_facloc: 0.0400
    de_facscale: 0.0237
    de_nu: 0.959
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    de_prob: 1
    down_prob: 0.5
    sim_model: splat
  cells_1000_groups_4:
    num_cells: 1000
    num_groups: 4
    num_batches: 1
    num_genes: 1000
    group_probs: 0.25,0.25,0.25,0.25
    batch_probs: "1"
    de_facloc: 0.0400
    de_facscale: 0.0237
    de_nu: 0.959
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    de_prob: 1
    down_prob: 0.5
    sim_model: splat
  cells_10000_groups_4:
    num_cells: 10000
    num_groups: 4
    num_batches: 1
    num_genes: 1000
    group_probs: 0.25,0.25,0.25,0.25
    batch_probs: "1"
    de_facloc: 0.0400
    de_facscale: 0.0237
    de_nu: 0.959
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    de_prob: 1
    down_prob: 0.5
    sim_model: splat
  cells_100000_groups_4:
    num_cells: 100000
    num_groups: 2
    num_batches: 1
    num_genes: 1000
    group_probs: 0.25,0.25,0.25,0.25
    batch_probs: "1"
    de_facloc: 0.0400
    de_facscale: 0.0237
    de_nu: 0.959
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    de_prob: 1
    down_prob: 0.5
    sim_model: splat
  cells_1000000_groups_4:
    num_cells: 1000000
    num_groups: 4
    num_batches: 1
    num_genes: 1000
    group_probs: 0.25,0.25,0.25,0.25
    batch_probs: "1"
    de_facloc: 0.0400
    de_facscale: 0.0237
    de_nu: 0.959
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    de_prob: 1
    down_prob: 0.5
    sim_model: splat


    
