# Pipeline directories
workdir: /datadrive/projects/cellassign-paper/results/scratch/novel_celltype_analysis/v1
outdir: /datadrive/projects/cellassign-paper/results/outputs/novel_celltype_analysis/v1
logdir: /datadrive/projects/cellassign-paper/results/logs/novel_celltype_analysis/v1

datasets:
  mcparland_liver: /datadrive/data/external/scrna/mcparland2018/human_liver.rds
  tian_3_10x: /datadrive/data/external/scrna/tian2018_qc/sce_sc_10x_qc.rds
  tian_3_CELseq2: /datadrive/data/external/scrna/tian2018_qc/sce_sc_CELseq2_qc.rds
  tian_3_Dropseq: /datadrive/data/external/scrna/tian2018_qc/sce_sc_Dropseq_qc.rds
  tian_mixture3: /datadrive/data/external/scrna/tian2018_qc/sce_SC3_qc.rds

preprocessing:
  mcparland_liver:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  tian_3_10x:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  tian_3_CELseq2:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  tian_3_Dropseq:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  tian_mixture3:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1


cellassign:
  mcparland_liver:
    liver_alldata_allmarkers:
      marker_list: ../../resources/marker_lists/liver_mcparland_alltypes.yaml
      include_other: TRUE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage
      celltypes: all
    liver_alldata_allmarkers_fixed:
      marker_list: ../../resources/marker_lists/liver_mcparland_alltypes_revised.yaml
      include_other: TRUE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage
      celltypes: all
    liver_3data_3markers:
      marker_list: ../../resources/marker_lists/liver_mcparland_3types.yaml
      include_other: FALSE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage
      celltypes: 
        - Cholangiocytes
        - Mature\ B\ cells
        - Hepatocytes
    liver_3data_allmarkers:
      marker_list: ../../resources/marker_lists/liver_mcparland_alltypes.yaml
      include_other: TRUE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage
      celltypes:
        - Cholangiocytes
        - Mature\ B\ cells
        - Hepatocytes
    liver_alldata_3markers:
      marker_list: ../../resources/marker_lists/liver_mcparland_alltypes.yaml
      include_other: TRUE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage
      celltypes: all
  


