# Pipeline directories
workdir: /datadrive/projects/cellassign-paper/results/scratch/novel_celltype_analysis/v1
outdir: /datadrive/projects/cellassign-paper/results/outputs/novel_celltype_analysis/v1
logdir: /datadrive/projects/cellassign-paper/results/logs/novel_celltype_analysis/v1

datasets:
  mcparland_liver: /datadrive/data/external/scrna/mcparland2018/human_liver.rds

preprocessing:
  mcparland_liver:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1


cellassign:
  mcparland_liver:
    liver_alldata_allmarkers:
      marker_list: # PATH TO MA[T
      include_other: TRUE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage TRUE
    liver_3data_3markers:
      marker_list: # PATH TO MARKER MAT
      include_other: FALSE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage TRUE
    liver_3data_allmarkers:
      marker_list: # PATH TO MAT
      include_other: TRUE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage TRUE
    liver_alldata_3markers:
      marker_list: # PATH TO MAT
      include_other: TRUE
      num_runs: 1
      B: 20
      design_formula: ~\ patient
      extra_opts: --shrinkage TRUE
  


