# Directories
workdir: '/datadrive/projects/cellassign-paper/results/scratch/main/v1'
outdir: '/datadrive/projects/cellassign-paper/results/outputs/main/v1'
logdir: '/datadrive/projects/cellassign-paper/results/logs/main/v1'

# Simulation results
simulation_analysis_results:
  deprob_result_dir: /datadrive/pipeline/results/cellassign-sim-comparison/resultsdeprob3
  wrongmarker_result_dir: /datadrive/pipeline/results/cellassign-sim-comparison/wrongmarkers2
  

# Follicular analysis results
follicular_analysis_results:
  sce_annotated: /datadrive/projects/cellassign-paper/results/outputs/follicular_analysis/v1/sce_follicular_annotated_final.rds
  sce_tcell_annotated: /datadrive/projects/cellassign-paper/results/outputs/follicular_analysis/v1/sce_annotated_subset/sce_follicular_tcells.rds
  sce_bcell_annotated: /datadrive/projects/cellassign-paper/results/outputs/follicular_analysis/v1/sce_annotated_subset/sce_follicular_bcells.rds
  differential_expression: 
    cytotoxic: /datadrive/projects/cellassign-paper/results/outputs/follicular_analysis/v1/differential_expression/celltype/cytotoxic.rds
    malignant: /datadrive/projects/cellassign-paper/results/outputs/follicular_analysis/v1/differential_expression/celltype/malignant.rds

# Dimensionality reduction type to plot
plot_dimreduce_type: 'UMAP'

# Follicular celltype labels
follicular_celltype_labels:
  tcell:
    - 'CD4\ \(activated\)'
    - 'Cytotoxic\ T\ cells\ \(activated\)'
    - 'Tfh'
    - 'Naive/resting\ CD4'
    - 'Cytotoxic\ T\ cells'
  bcell:
    - 'B\ cells'
    - 'B\ cells\ \(malignant\)'

# External data
external:
  azizi_s4: "/datadrive/projects/cellassign-paper/resources/external/azizi2018/Table_S4.xls"