configfile: "config/v1.yaml"

singularity: "docker://alzhang/scrna-analysis-sim-3.5:v1.9"

rule all:
    input:
        '{workdir}/sce_follicular.rds'.format(workdir=config['workdir']),
        #follicular_annotated='{workdir}/sce_follicular_annotated.rds'.format(outdir=config['workdir']),


# Create SingleCellExperiment
rule create_follicular_sce:
    input:
        filtered_matrices=[x['filtered_matrix_path'] for x in config['follicular_data']],
    output:
        '{workdir}/sce_follicular.rds'.format(workdir=config['workdir'])
    params:
        name='create-follicular-sce',
        sample_names=[x['dataset'] for x in config['follicular_data']],
        timepoints=[x['timepoint'] for x in config['follicular_data']],
        progression_statuses=[x['progression_status'] for x in config['follicular_data']],
        patient_progression_statuses=[x['patient_progression_status'] for x in config['follicular_data']],
        patients=[x['patient'] for x in config['follicular_data']],
    log:
        '{logdir}/logs/create_follicular_sce.log'.format(logdir=config['logdir'])
    benchmark:
        '{logdir}/benchmarks/create_follicular_sce.txt'.format(logdir=config['logdir'])
    shell:
        'Rscript R/create_sce.R --sample_names {params.sample_names} --filtered_matrices {input.filtered_matrices} '
        '--timepoints {params.timepoints} --progression {params.progression} --patient_progression {params.patient_progression}'
        '--patients {params.patients} --outfname {output} &> {log}'


# Filter and normalize SingleCellExperiment
rule preprocess_follicular_sce:
    input:
        follicular_raw='{workdir}/sce_follicular.rds'.format(workdir=config['workdir']),
    output:
        follicular_normalized='{workdir}/sce_follicular_normalized.rds'.format(workdir=config['workdir']),
    params:
        name='preprocess-follicular-sce',
        mito_thres=config['mito_thres'],
        ribo_thres=config['ribo_thres'],
    shell:
        ''

# Cell cycle assignments (TODO: Run this in multi-core mode)
rule cyclone_follicular_sce:
    input:
        follicular_normalized='{workdir}/sce_follicular_normalized.rds'.format(workdir=config['workdir']),
    output:
        cc_top='{outdir}/cyclone/cc_top_assignments.txt'.format(outdir=config['outdir']),
        cc_scores='{outdir}/cyclone/cc_scores.tsv'.format(outdir=config['outdir']),
    params:
        name='cyclone-follicular-sce',
    shell:
        ''

# Assign cells to B or T classes
rule cellassign_follicular_small:
    input:
        follicular_normalized='{workdir}/sce_follicular_normalized.rds'.format(workdir=config['workdir']),
    output:
        broad_assignments='{outdir}/broad_assignments.rds'.format(outdir=config['outdir']),
    params:
        name='cellassign-follicular-small',
    shell:
        ''

# Assign cells to specific subtypes, including cytotoxic T
rule cellassign_follicular_big:
    input:
        follicular_normalized='{workdir}/sce_follicular_normalized.rds'.format(workdir=config['workdir']),
    output:
        specific_assignments='{outdir}/specific_assignments.rds'.format(outdir=config['outdir']),
    params:
        name='cellassign-follicular-big',
    shell:
        ''

# Unsupervised clustering of T cells
rule follicular_unsupervised_t:
    input:
        follicular_normalized='{workdir}/sce_follicular_normalized.rds'.format(workdir=config['workdir']),
    output:
        unsupervised_t_assignments='{outdir}/unsupervised_t_assignments.rds'.format(outdir=config['outdir']),
    params:
        name='follicular-unsupervised-t',
        random_seed=config['cluster_random_seed'],
        cluster_methods=config['cluster_settings']['follicular_t']['methods'],
        cluster_use_method=config['cluster_settings']['follicular_t']['use_method'],
    shell:
        ''

# Unsupervised clustering of malignant B cells
rule follicular_unsupervised_malignant:
    input:
        follicular_normalized='{workdir}/sce_follicular_normalized.rds'.format(workdir=config['workdir']),
    output:
        unsupervised_malignant_assignments='{outdir}/unsupervised_malignant_assignments.rds'.format(outdir=config['outdir']),
    params:
        name='follicular-unsupervised-malignant',
        random_seed=config['cluster_random_seed'],
        cluster_methods=config['cluster_settings']['follicular_malignant']['methods'],
        cluster_use_method=config['cluster_settings']['follicular_malignant']['use_method'],
    shell:
        ''

# Unsupervised clustering of nonmalignant B cells
rule follicular_unsupervised_b:
    input:
        follicular_normalized='{workdir}/sce_follicular_normalized.rds'.format(workdir=config['workdir']),
    output:
        unsupervised_b_assignments='{outdir}/unsupervised_b_assignments.rds'.format(outdir=config['outdir']),
    params:
        name='follicular-unsupervised-b',
        random_seed=config['cluster_random_seed'],
        cluster_methods=config['cluster_settings']['follicular_b']['methods'],
        cluster_use_method=config['cluster_settings']['follicular_b']['use_method'],
    shell:
        ''

# Annotate follicular SCE with assignments
rule annotate_follicular:
    input:
        follicular_normalized='{workdir}/sce_follicular_normalized.rds'.format(workdir=config['workdir']),
        broad_assignments='{outdir}/broad_assignments.rds'.format(workdir=config['outdir']),
        specific_assignments='{outdir}/specific_assignments.rds'.format(workdir=config['outdir']),
        unsupervised_t_assignments='{outdir}/unsupervised_t_assignments.rds'.format(outdir=config['outdir']),
        unsupervised_malignant_assignments='{outdir}/unsupervised_malignant_assignments.rds'.format(outdir=config['outdir']),
        unsupervised_b_assignments='{outdir}/unsupervised_b_assignments.rds'.format(outdir=config['outdir']),
    output:
        follicular_annotated='{workdir}/sce_follicular_annotated.rds'.format(outdir=config['workdir']),
    params:
        name='annotate-follicular',
    shell:
        ''

