# Directories
workdir: '/datadrive/projects/cellassign-paper/results/scratch/v1'
outdir: '/datadrive/projects/cellassign-paper/results/outputs/v1'
logdir: '/datadrive/projects/cellassign-paper/results/logs/v1'

# Random seeds
cluster_random_seed: 19279

# Sample names (in same order as filtered matrices)
follicular_sample_names:
  - FL1018T1
  - FL1018T2

# Paths to filtered gene expression matrices
follicular_data:
  FL1018T1:
    dataset: FL1018T1
    patient: FL1018
    timepoint: T1
    progression_status: primary
    patient_progression_status: transformed
    filtered_matrix_path: '/datadrive/data/follicular/FL1018T1/filtered_gene_bc_matrices/GRCh38'
  FL1018T2:
    dataset: FL1018T2
    patient: FL1018
    timepoint: T2
    progression_status: transformed
    patient_progression_status: transformed
    filtered_matrix_path: '/datadrive/data/follicular/FL1018T2/filtered_gene_bc_matrices/GRCh38'

# Unsupervised clustering settings
cluster_settings:
  follicular_t:
    methods: 
      - 'seurat_0.8'
      - 'phenograph'
    use_method: 'seurat'
    celltypes:
      - CD4\ \(activated\)
      - Cytotoxic\ T\ cells\ \(activated\)
      - Tfh
      - Naive/resting\ CD4
      - Cytotoxic\ T\ cells
  follicular_b:
    methods: 
      - 'seurat_0.8'
      - 'phenograph'
    use_method: 'phenograph'
    celltypes:
      - B\ cells
  follicular_malignant:
    methods:
      - 'seurat_0.8'
      - 'phenograph'
    use_method: 'phenograph'
    celltypes:
      - B\ cells\ \(malignant\)

# Filtering thresholds
filter_settings:
  mito_thres: 10
  ribo_thres: 60

# Marker list matrices for CellAssign
marker_lists:
  small: 
    path: '/datadrive/projects/cellassign-paper/resources/marker_lists/follicular_small.yaml'
    include_other: TRUE
  big: 
    path: '/datadrive/projects/cellassign-paper/resources/marker_lists/follicular_big.yaml'
    include_other: TRUE

# CellAssign settings
cellassign_settings:
  num_runs: 1
  B: 20
  extra_opts: "--delta_prior"
  threads: 18

# Differential expression settings
differential_expression_celltype_groups:
  cytotoxic:
    - Cytotoxic\ T\ cells
    - Cytotoxic\ T\ cells\ \(activated\)
  follicular_helper:
    - Tfh
  malignant:
    - B\ cells\ \(malignant\)
  b:
    - B\ cells
  helper:
    - CD4\ \(activated\)
    - Naive/resting\ CD4

gene_set: '/datadrive/projects/cellassign-analysis/downloads/c2.cp.reactome.v6.2.symbols.gmt'

# Probabilities to filter celltypes at (for post-annotation filtering jobs)
celltype_filters:
  broad_t_cell_probability: 0.9