---
title: "Cell classification -- rare type detection"
output: html_notebook
---

```{r global_chunk_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, warning = FALSE, message = FALSE, cache = TRUE, cache.lazy = FALSE, fig.width = 8, fig.height = 4.5)
```

```{r, echo = FALSE}
library(knitr)
library(tidyverse)
library(tensorflow)
library(SingleCellExperiment)
library(scater)
library(data.table)
library(pheatmap)
library(ggrepel)
library(scran)
library(BiocParallel)
library(limma)
library(edgeR)
library(GSEABase)
library(scvis)
library(future)
library(splatter)
library(infotheo)

library(scrna.utils)
library(scrna.sceutils)
library(cellassign)
library(cellassign.utils)

environment(read10xResults2) <- asNamespace("scater")

plan(multiprocess)
```

## splatter simulate

```{r, echo = FALSE}
sce_t4k <- readRDS("/datadrive/projects/cellassign-analysis/pipelines/simulate-toil/test/sce_t4k.rds")
```

```{r, echo = FALSE}
model_params <- readRDS("/datadrive/projects/cellassign-analysis/pipelines/simulate-toil/test/sce_t4k_params.rds")

#model_params <- splatEstimate(as.matrix(counts(sce_t4k)))
```

```{r, echo = FALSE}
#saveRDS(model_params, "/datadrive/projects/cellassign-analysis/pipelines/simulate-toil/test/sce_t4k_params.rds")
```

```{r, echo = FALSE}
num_groups <- 3
num_batches <- 1
num_cells <- 1500

# CellAssign does better. But this is a hard problem because there's usually 1 cluster with no high delta (logFC) relative to the others. 
naive_cd8_cd4_params <- c('de_facscale'=0.015, 'de_facloc'=0.03, 'de_facnu'=1.5,
                          'down_prob'=0.12, 'de_prob'=0.07, 'de_max'=100, 'de_min'=1)
naive_cd8_cd4_params_v2 <- c('de_facscale'=0.015, 'de_facloc'=0.03, 'de_facnu'=1.3,
                          'down_prob'=0.12, 'de_prob'=0.14, 'de_max'=1000, 'de_min'=1)
naive_cd8_cd4_params_v3 <- c('de_facscale'=0.015, 'de_facloc'=0.03, 'de_facnu'=1.3,
                          'down_prob'=0.12, 'de_prob'=0.21, 'de_max'=1000, 'de_min'=1)

# CellAssign still does better. 
b_cd8_params <- c('de_facscale'=0.015, 'de_facloc'=0.024, 'de_facnu'=1,
                          'down_prob'=0.52, 'de_prob'=0.23, 'de_max'=100, 'de_min'=1)
b_cd8_params_v2 <- c('de_facscale'=0.015, 'de_facloc'=0.048, 'de_facnu'=1,
                          'down_prob'=0.52, 'de_prob'=0.23, 'de_max'=1000, 'de_min'=1)
b_cd8_params_v3 <- c('de_facscale'=0.015, 'de_facloc'=0.036, 'de_facnu'=1,
                          'down_prob'=0.52, 'de_prob'=0.23, 'de_max'=1000, 'de_min'=1)
b_cd8_params_v4 <- c('de_facscale'=0.015, 'de_facloc'=0.030, 'de_facnu'=1,
                          'down_prob'=0.52, 'de_prob'=0.23, 'de_max'=1000, 'de_min'=1)

# CellAssign still does better. Harder problem because fewer outliers, but we don't do too poorly. 
hgsc_mono_cd8_params <- c('de_facscale'=0.11, 'de_facloc'=0.023, 'de_facnu'=2,
                          'down_prob'=0.7, 'de_prob'=0.11, 'de_max'=100, 'de_min'=1)
hgsc_mono_cd8_params_v2 <- c('de_facscale'=0.11, 'de_facloc'=0.035, 'de_facnu'=2,
                          'down_prob'=0.7, 'de_prob'=0.11, 'de_max'=100, 'de_min'=1)
hgsc_mono_cd8_params_v3 <- c('de_facscale'=0.11, 'de_facloc'=0.046, 'de_facnu'=2,
                          'down_prob'=0.7, 'de_prob'=0.11, 'de_max'=100, 'de_min'=1)
hgsc_mono_cd8_params_v4 <- c('de_facscale'=0.15, 'de_facloc'=0.023, 'de_facnu'=2,
                          'down_prob'=0.7, 'de_prob'=0.11, 'de_max'=100, 'de_min'=1)

# CellAssign: use 99% logFC threshold because there are so many genes
hgsc_endo_fibro_params <- c('de_facscale'=0.044, 'de_facloc'=0.07, 'de_facnu'=1.23,
                          'down_prob'=0.15, 'de_prob'=0.46, 'de_max'=100, 'de_min'=1)


params <- b_cd8_params

seed <- 8423
sim_model <- "splat"
group_probs <- rep(1/num_groups, num_groups)
batch_cells <- rep(num_cells/num_batches, num_batches)

model_params_modified <- model_params

model_params_modified@nCells <- num_cells
model_params_modified@de.prob <- params['de_prob']
model_params_modified@nBatches <- num_batches
model_params_modified@batchCells <- batch_cells
model_params_modified@nGroups <- num_groups
model_params_modified@group.prob <- group_probs
model_params_modified@de.downProb <- params['down_prob']

model_params_modified@de.facLoc <- params['de_facloc']
model_params_modified@de.facScale <- params['de_facscale']
model_params_modified@de.facNu <- params['de_facnu']
model_params_modified@de.max <- params['de_max']
model_params_modified@de.min <- params['de_min']

model_params_modified@seed <- seed
```

```{r, echo = FALSE}
sce_sim <- splatSimulate(params = model_params_modified, method = "groups", verbose = TRUE)
```


```{r, echo = FALSE}
sce_sim <- normalize_sce_sim(sce_sim, run_dimred = TRUE)
```

```{r, echo = FALSE}
plotPCA(sce_sim, ncomponents = 2, colour_by = "Group")
```

```{r, echo = FALSE}
plotTSNE(sce_sim, ncomponents = 2, colour_by = "Group")
```

## CellAssign

```{r, echo = FALSE}
s <- sizeFactors(sce_sim)
B <- 20
X <- NULL

markers_to_use <- select_markers(sce_sim, percentile_fc = 0.95, percentile_meanexpr = 0.8, frac_genes = 1) # 0.99
## CONSTRUCT RHO FROM VALUES IN sce_sim -- CHECK OLD CODE

rho <- create_rho_matrix(sce_sim, markers_to_use)
```

```{r, echo = FALSE}
res <- cellassign_em(exprs_obj = sce_sim[rownames(rho),], s = s, rho = rho, X = X, B = B, use_priors = FALSE, prior_type = "shrinkage", delta_variance_prior = FALSE, verbose = FALSE, em_convergence_thres = 1e-5, min_delta = 0)
```

```{r, echo = FALSE}
sce_sim$celltype <- res$cell_type

plotTSNE(sce_sim, colour_by = "celltype")
```


### Delta

```{r, echo = FALSE}
compare_res <- delta_compare(sce_sim[rownames(rho),], res, colour_by = "Group", shape_by = "high_expr")

compare_res$p
```

```{r, echo = FALSE}
table(res$cell_type, sce_sim$Group)
```

```{r, echo = FALSE}
eval_measures <- compute_evaluation_measures(sce_sim, 
                                             truth_labels = sce_sim$Group,
                                             inferred_labels = sce_sim$celltype)

eval_measures
```


## Unsupervised clustering and classification (all genes)

```{r, echo = FALSE}
cluster_wrapper <- function(sce, gene_subset = NULL, dimreduce_method, clustering_method, seurat_resolution = 0.6, object2 = NULL, object2_cluster_label = "Group") {
  if (!is.null(gene_subset)) {
    sce <- sce[gene_subset,]
    sce <- runPCA(sce, ntop = 500, ncomponents = 50, exprs_values = "logcounts")
    
    if (!is.null(object2)) {
      object2 <- object2[gene_subset,]
    }
  }
  
  if (clustering_method == "phenograph") {
    sce_clustered <- cluster_cells(sce, method = clustering_method, dimreduce_type = dimreduce_method, conda_env = "r-tensorflow", phenograph_module = "scrnatools.methods.clustering.phenograph_analysis")
  } else if (clustering_method == "dbscan") {
    sce_clustered <- cluster_cells(sce, method = clustering_method, dimreduce_type = dimreduce_method, dbscan_epsilon = 0.5, dbscan_minPoints = 5)
  } else if (clustering_method == "seurat") {
    sce_clustered <- cluster_cells(sce, method = clustering_method, dimreduce_type = dimreduce_method,
                                   seurat_resolution = seurat_resolution)
  } else if (clustering_method %in% c("Zheng_cor", "scmap")) {
    sce_clustered <- cluster_cells(sce, method = clustering_method, dimreduce_type = dimreduce_method,
                                   object2 = object2, object2_cluster_label = object2_cluster_label)
  } else {
    sce_clustered <- cluster_cells(sce, method = clustering_method, dimreduce_type = dimreduce_method)
  }
  return(sce_clustered)
}
```

```{r, echo = FALSE}
sce_sim <- cluster_wrapper(sce_sim, gene_subset = NULL, dimreduce_method = "PCA", clustering_method = "phenograph")
```

```{r, echo = FALSE}
table(sce_sim$cluster, sce_sim$Group)
```

```{r, echo = FALSE}
map_and_evaluate_clusters <- function(sce_sim, min_count = 0) {
  # Remove genes that are lowly expressed, and cells with no UMIs
  sce_sim <- sce_sim[rowSums(counts(sce_sim)) >= min_count,colSums(counts(sce_sim)) > 0]
  
  nclusts <- length(unique(sce_sim$cluster))
  
  if (nclusts > 1) {
    sce_de <- map_clusters(sce_sim, method = "de2", FDR_cutoff = 0.05)
    sce_correlation <- map_clusters(sce_sim, method = "correlation", min_correlation = 0)
  } else {
    max_group <- names(which.max(table(sce_sim$Group)))[1]
    
    sce_de <- sce %>% scater::mutate(inferred_group=max_group)
    sce_correlation <- map_clusters(sce_sim, method = "correlation", min_correlation = 0)
  }
  
  de_evaluation_measures <- compute_evaluation_measures(sce_de, 
                                                         truth_labels = sce_de$Group,
                                                         inferred_labels = sce_de$inferred_group)
  corr_evaluation_measures <- compute_evaluation_measures(sce_correlation, 
                                                           truth_labels = sce_correlation$Group,
                                                           inferred_labels = sce_correlation$inferred_group)
  
  evaluation_measures <- rbind(data.frame(mapping_type = "de", de_evaluation_measures, stringsAsFactors = FALSE), data.frame(mapping_type = "correlation", corr_evaluation_measures, stringsAsFactors = FALSE))
  
  return(evaluation_measures)
}
```

```{r, echo = FALSE}
evaluation_measures <- map_and_evaluate_clusters(sce_sim)

evaluation_measures
```

## Unsupervised clustering and classification (marker genes)

```{r, echo = FALSE}
sce_sim_markers <- cluster_wrapper(sce_sim, gene_subset = markers_to_use, dimreduce_method = "PCA", clustering_method = "phenograph")
```

```{r, echo = FALSE}
table(sce_sim_markers$cluster, sce_sim_markers$Group)
```

```{r, echo = FALSE}
evaluation_measures_markers <- map_and_evaluate_clusters(sce_sim_markers, min_count = 1)

evaluation_measures_markers
```


## Seurat testing

```{r, echo = FALSE}
sce_seurat_test <- cluster_wrapper(sce_sim, dimreduce_method = "PCA", clustering_method = "seurat", seurat_resolution = 0.6)
```

IGNORE THE BELOW. 

```{r}
# devtools::install_github('satijalab/Seurat', ref = "release/3.0")
# devtools::install("/datadrive/projects/seurat")

library(Seurat)

sce_sim_minimal <- sce_sim
#reducedDims(sce_sim_minimal) <- NULL
#n_top_genes <- 1000

seurat_sim <- Convert(from = sce_sim_minimal, to = "seurat")
seurat_sim <- FindVariableGenes(object = seurat_sim,
                                mean.function = ExpMean,
                                dispersion.function = LogVMR,
                                x.low.cutoff = 0.0125,
                                x.high.cutoff = 3,
                                y.cutoff = 0.5)

#top_genes <- rownames(HVFInfo(object = seurat_sim))[which(HVFInfo(object = seurat_sim)[["variance"]] > sort(HVFInfo(object = seurat_sim)[["variance"]], decreasing = TRUE)[n_top_genes])]
seurat_sim <- ScaleData(object = seurat_sim, vars.to.regress = c()) #c("total_counts")

seurat_sim <- RunPCA(object = seurat_sim, pc.genes = seurat_sim@var.genes, pcs.compute = 50)

resolutions <- seq(0.3, 1.5, 0.1)

#seurat_sim <- BuildSNN(seurat_sim)
seurat_sim <- FindClusters(seurat_sim, reduction.type = 'PCA', dims.use = 1:50, resolution = 0.9)
```

```{r}
DimPlot(object = seurat_sim, reduction = 'PCA')
```

```{r}
sce_sim_minimal$cluster <- seurat_sim@meta.data$res.0.9
```

```{r, echo = FALSE}
table(sce_sim_minimal$cluster, sce_sim_minimal$Group)
```

```{r, echo = FALSE}
evaluation_measures_seurat <- map_and_evaluate_clusters(sce_sim_minimal, min_count = 1)

evaluation_measures_seurat
```

```{r}
library(scmap)
library(splitstackshape)
library(MetaNeighbor)

# devtools::install_github('IMB-Computational-Genomics-Lab/scPred')
```

```{r}
truth_proportion <- 0.5

coldat <- as.data.frame(colData(sce_sim))

sets <- splitstackshape::stratified(coldat, group = "Group", size = truth_proportion, bothSets = TRUE)

rowData(sce_sim)$feature_symbol <- rowData(sce_sim)$Gene

sim_train <- sce_sim[,which(as.character(colData(sce_sim)$Cell) %in% as.character(sets$SAMP1$Cell))]
sim_test <- sce_sim[,which(as.character(colData(sce_sim)$Cell) %in% as.character(sets$SAMP2$Cell))]
```

```{r}
sim_train <- scmap::selectFeatures(sim_train, suppress_plot = TRUE)
sim_train <- scmap::indexCluster(sim_train, cluster_col = "Group")
```

```{r}
heatmap(as.matrix(metadata(sim_train)$scmap_cluster_index))
```

```{r}
test_to_train <- scmap::scmapCluster(
  projection = sim_test, 
  index_list = list(
    sim_train = metadata(sim_train)$scmap_cluster_index
  )
)

sim_test$cluster <- factor(test_to_train$scmap_cluster_labs)
```

```{r, echo = FALSE}
table(sim_test$cluster, sim_test$Group)
```

```{r, echo = FALSE}
evaluation_measures_test <- map_and_evaluate_clusters(sim_test, min_count = 1)

evaluation_measures_test
```

```{r}
train_data <- t(logcounts(sim_train))
test_data <- t(logcounts(sim_test))
train_metadata <- as.data.frame(colData(sim_train)) 
test_metadata <- as.data.frame(colData(sim_test))
train_metadata$Group <- factor(train_metadata$Group)
test_metadata$Group <- factor(test_metadata$Group)
```

```{r, echo = FALSE}
library(scPred)

set.seed(1234)
scp <- eigenDecompose(train_data, n = 10, pseudo = FALSE)
scPred::metadata(scp) <- train_metadata
scp <- getFeatureSpace(scp, pVar = "Group")
```

```{r}
scp <- trainModel(scp, seed = 66)
```

```{r}
predictions <- scPredict(scp, newData = test_data, threshold = 0.9)

sim_test$cluster <- predictions$predClass
```

```{r, echo = FALSE}
table(sim_test$cluster, sim_test$Group)
```

## Max correlation method

```{r}
## TODO: Make some of my own methods that do min-distance or max correlation when mapping
## i.e. map each cell to its max correlation true cluster

max_cor_clustering <- function(train_data, test_data, train_metadata, min_cor = 0, cluster_col = "Group") {
  # Compute cluster means
  unique_clusters <- unique(train_metadata[,cluster_col])
  cluster_means <- do.call(rbind, lapply(unique_clusters, function(clust) {
    idx <- which(train_metadata[,cluster_col] == clust)
    exprs <- colMeans(train_data[idx,])
    return(exprs)
  }))
  rownames(cluster_means) <- unique_clusters
  
  # Map each cell to its max cor cluster
  cors <- cor(t(test_data), t(cluster_means))
  mapped_groups <- apply(cors, 1, function(x) ifelse(max(x) >= min_cor, colnames(cors)[which.max(x)], NA))
  
  return(mapped_groups)
}

mapped_clusters <- max_cor_clustering(train_data, test_data, train_metadata, 
                                      min_cor = 0, cluster_col = "Group")

sim_test$cluster <- mapped_clusters
```

```{r}
plotTSNE(sim_test, colour_by = "cluster")
```

```{r, echo = FALSE}
table(sim_test$cluster, sim_test$Group)
```

```{r, echo = FALSE}
evaluation_measures_test <- map_and_evaluate_clusters(sim_test, min_count = 1)

evaluation_measures_test
```

```{r, echo = FALSE}
sce_sim_cor <- cluster_wrapper(sim_test, gene_subset = markers_to_use, dimreduce_method = "PCA", clustering_method = "Zheng_cor", object2 = sim_train, object2_cluster_label = "Group")
```

```{r, echo = FALSE}
table(sce_sim_cor$cluster, sce_sim_cor$Group)
```

```{r, echo = FALSE}
evaluation_measures_test <- map_and_evaluate_clusters(sce_sim_cor, min_count = 1)

evaluation_measures_test
```

```{r, echo = FALSE}
sce_sim_scmap <- cluster_wrapper(sim_test, gene_subset = markers_to_use, dimreduce_method = "PCA", clustering_method = "scmap", object2 = sim_train, object2_cluster_label = "Group")
```

```{r, echo = FALSE}
table(sce_sim_scmap$cluster, sce_sim_scmap$Group)
```

```{r, echo = FALSE}
evaluation_measures_test <- map_and_evaluate_clusters(sce_sim_scmap, min_count = 1)

evaluation_measures_test
```

