workdir: ../../results/scratch/novel_missing_simulation_analysis/custom_params
outdir: ../../results/outputs/novel_missing_simulation_analysis/custom_params
logdir: ../../results/logs/novel_missing_simulation_analysis/custom_params


simulation_settings:
  variables:
    de_prob:
      - 0.25
    down_prob:
      - 0.5
    seed:
      - 8123
      - 3143
      - 8423
      - 1719
      - 5011
      - 1594
      - 3419
      - 1258
      - 6255
  constants:
    num_cells: 1000
    num_groups: 6
    group_probs:
      - 0.16
      - 0.16
      - 0.17
      - 0.17
      - 0.17
      - 0.17
    num_batches: 1
    batch_probs:
      - 1
    de_facloc: 0.04
    de_facscale: 0.02
    de_nu: 1
    de_min: 1
    de_max: 1000
    batch_facloc: 1
    batch_facscale: 1
    base_params: ../cellassign-sim-comparison/data/sce_t4k_params.rds

assign_celltype_settings:
  methods:
    - cellassign
    - scina
    - scina_0.1
  conda_env: r-tensorflow
  fc_percentile: 0.95
  expr_percentile: 0.9
  frac_genes: 1
  max_genes: 
    - 30
  wrong_marker_proportion: 
    - 0
  runs:
    novel0:
      data_celltypes:
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
      marker_celltypes: 
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
    novel1:
      data_celltypes:
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
      marker_celltypes: 
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
    novel2:
      data_celltypes:
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
      marker_celltypes: 
        - Group1
        - Group2
        - Group3
        - Group4
    novel3: 
      data_celltypes:
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
      marker_celltypes: 
        - Group1
        - Group2
        - Group3
    novel4:
      data_celltypes:
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
      marker_celltypes: 
        - Group1
        - Group2
    novel5:
      data_celltypes:
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
      marker_celltypes: 
        - Group1
    superset1:
      data_celltypes:
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
      marker_celltypes: 
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
    superset2:
      data_celltypes:
        - Group1
        - Group2
        - Group3
        - Group4
      marker_celltypes: 
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
    superset3:
      data_celltypes:
        - Group1
        - Group2
        - Group3
      marker_celltypes: 
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6
    superset4:
      data_celltypes:
        - Group1
        - Group2
      marker_celltypes: 
        - Group1
        - Group2
        - Group3
        - Group4
        - Group5
        - Group6