# Pipeline directories
workdir: /datadrive/projects/cellassign-paper/results/scratch/real_data_benchmarking/v1
outdir: /datadrive/projects/cellassign-paper/results/outputs/real_data_benchmarking/v1
logdir: /datadrive/projects/cellassign-paper/results/logs/real_data_benchmarking/v1

datasets:
  mcparland_liver: /datadrive/data/external/scrna/mcparland2018/human_liver.rds
  tian_3_10x: /datadrive/data/external/scrna/tian2018_qc/sce_sc_10x_qc.rds
  tian_3_CELseq2: /datadrive/data/external/scrna/tian2018_qc/sce_sc_CELseq2_qc.rds
  tian_3_Dropseq: /datadrive/data/external/scrna/tian2018_qc/sce_sc_Dropseq_qc.rds
  tian_mixture3: /datadrive/data/external/scrna/tian2018_qc/sce_SC3_qc.rds
  follicular: /datadrive/projects/cellassign-paper/results/outputs/follicular_analysis/v4/sce_follicular_annotated_final.rds

preprocessing:
  mcparland_liver:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  tian_3_10x:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  tian_3_CELseq2:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  tian_3_Dropseq:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  tian_mixture3:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1
  follicular:
    nmads: Inf
    max_mito: 100
    max_ribo: 100
    umap_neighbors: 15
    umap_min_dist: 0.1


cellassign:
  liver_alldata_allmarkers:
    dataset: mcparland_liver
    marker_list: ../../resources/marker_lists/liver_mcparland_alltypes.yaml
    include_other: TRUE
    num_runs: 1
    B: 20
    design_formula: ~\ patient
    extra_opts: --shrinkage
    celltypes: all
  liver_alldata_allmarkers_fixed:
    dataset: mcparland_liver
    marker_list: ../../resources/marker_lists/liver_mcparland_alltypes_revised.yaml
    include_other: TRUE
    num_runs: 1
    B: 20
    design_formula: ~\ patient
    extra_opts: --shrinkage
    celltypes: all
  liver_3data_3markers:
    dataset: mcparland_liver
    marker_list: ../../resources/marker_lists/liver_mcparland_3types.yaml
    include_other: FALSE
    num_runs: 1
    B: 20
    design_formula: ~\ patient
    extra_opts: --shrinkage
    celltypes: 
      - Cholangiocytes
      - Mature\ B\ cells
      - Hepatocytes
  liver_3data_allmarkers:
    dataset: mcparland_liver
    marker_list: ../../resources/marker_lists/liver_mcparland_alltypes.yaml
    include_other: TRUE
    num_runs: 1
    B: 20
    design_formula: ~\ patient
    extra_opts: --shrinkage
    celltypes:
      - Cholangiocytes
      - Mature\ B\ cells
      - Hepatocytes
  liver_alldata_3markers:
    dataset: mcparland_liver
    marker_list: ../../resources/marker_lists/liver_mcparland_3types.yaml
    include_other: TRUE
    num_runs: 1
    B: 20
    design_formula: ~\ patient
    extra_opts: --shrinkage
    celltypes: all
  liver_alldata_3markers_2: # To show that ab T cells and gd T cells will get confused due to similarity
    dataset: mcparland_liver
    marker_list: ../../resources/marker_lists/liver_mcparland_3types_2.yaml
    include_other: TRUE
    num_runs: 1
    B: 20
    design_formula: ~\ patient
    extra_opts: --shrinkage
    celltypes: all
  tian_20markers:
    dataset:
      - tian_3_CELseq2
      - tian_mixture3
    marker_list: ../../resources/marker_lists/tian_20_73_markers.yaml
    include_other: FALSE
    num_runs: 3
    B: 20
    design_formula: ~\ path
    extra_opts: --shrinkage
    celltypes: all
  tian_30markers:
    dataset:
      - tian_3_CELseq2
      - tian_mixture3
    marker_list: ../../resources/marker_lists/tian_30_73_markers.yaml
    include_other: FALSE
    num_runs: 3
    B: 20
    design_formula: ~\ path
    extra_opts: --shrinkage
    celltypes: all
  tian_50markers:
    dataset:
      - tian_3_CELseq2
      - tian_mixture3
    marker_list: ../../resources/marker_lists/tian_50_73_markers.yaml
    include_other: FALSE
    num_runs: 3
    B: 20
    design_formula: ~\ path
    extra_opts: --shrinkage
    celltypes: all
  follicular_lk_full:
    dataset: follicular
    marker_list: ../../resources/marker_lists/follicular_merged_lk.yaml
    include_other: FALSE
    num_runs: 3
    B: 20
    design_formula: ~\ patient
    extra_opts: --shrinkage
    celltypes: all



