# Naive CD4+ vs. CD8+ extra seeds

script_file:
  class: File
  path: /root/cellassign-paper/pipelines/cellassign-sim-comparison/R/rmarkdown_wrapper.R
simulate_rmd_file: 
  class: File
  path: /root/cellassign-paper/pipelines/cellassign-sim-comparison/Rmd/simulate_sce.Rmd
cluster_rmd_file:
  class: File
  path: /root/cellassign-paper/pipelines/cellassign-sim-comparison/Rmd/cluster_cells.Rmd
random_seeds:
  - 6812
  - 1249
  - 2159
  - 8172
  - 1205
  - 6592
  - 1021
  - 5522
  - 6124
num_cellss:
  - 2000
test_proportions: 
  - 0.5
sim_model: splat
num_groupss:
  - 3
num_batchess:
  - 1
group_probss:
  - 0.33,0.33,0.34
batch_probss:
  - '1'
de_faclocs:
  - 0.028
de_facscales:
  - 0.015
de_nus:
  - 1.35
de_min: 1
de_max: 1000
batch_faclocs:
  - 1
batch_facscales:
  - 1
de_probs:
  - 0.05
  - 0.15
  - 0.25
  - 0.35
  - 0.45
  - 0.55
down_probs:
  - 0.5
dimreduce_methods:
  - PCA
clustering_methods:
  - cellassign
  - cellassign_shrinkage
  - phenograph
  - SC3
  - kmeans
  - seurat_0.4
  - seurat_0.8
  - seurat_1.2
  - densitycut
  - scmap
  - Zheng_cor
  - dynamicTreeCut
conda_env: r-tensorflow
fc_percentiles:
  - 0.95
expr_percentiles: 
  - 0.9
frac_geness:
  - 1
max_geness:
  - 15
wrong_marker_proportions:
  - 0
base_sce_params:
  - {class: File, path: /root/cellassign-paper/pipelines/cellassign-sim-comparison/data/sce_t4k_params.rds}
