script_file:
  class: File
  path: /root/cellassign-paper/pipelines/cellassign-sim-comparison/R/rmarkdown_wrapper.R
simulate_rmd_file: 
  class: File
  path: /root/cellassign-paper/pipelines/cellassign-sim-comparison/Rmd/simulate_sce.Rmd
cluster_rmd_file:
  class: File
  path: /root/cellassign-paper/pipelines/cellassign-sim-comparison/Rmd/cluster_cells.Rmd
random_seeds:
  - 8123
  - 3143
  - 8423
  - 1719
  - 5011
  - 1594
  - 3419
  - 1258
  - 6255
num_cellss:
  - 1500
test_proportions: 
  - 1
sim_model: splat
num_groupss:
  - 3
num_batchess:
  - 1
group_probss:
  - 0.33,0.33,0.34
batch_probss:
  - '1'
de_faclocs:
  - 0.015
de_facscales:
  - 0.03
  - 0.06
  - 0.09
de_nus:
  - 1
de_min: 1
de_max: 1000
batch_faclocs:
  - 1
batch_facscales:
  - 1
de_probs:
  - 0.25
down_probs:
  - 0.5
dimreduce_methods:
  - PCA
clustering_methods:
  - cellassign
  - cellassign_shrinkage
conda_env: r-tensorflow
fc_percentiles:
  - 0.95
expr_percentiles: 
  - 0.9
frac_geness:
  - 1
max_geness:
  - 15
  - 30
wrong_marker_proportions:
  - 0
  - 0.2
  - 0.4
  - 0.6
  - 0.8
  - 0.9
  - 0.95
base_sce_params:
  - {class: File, path: /root/cellassign-paper/pipelines/cellassign-sim-comparison/data/sce_t4k_params.rds}
